# Generated by Django 5.0.1 on 2024-04-02 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_num', models.IntegerField(null=True)),
                ('players_connected', models.IntegerField(default=0)),
                ('total_pot', models.IntegerField(default=0)),
                ('curr_round', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StuffCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('T', 'Ten'), ('J', 'Jack'), ('Q', 'Queen'), ('K', 'King'), ('A', 'Ace')], max_length=5, null=True)),
                ('suit', models.CharField(choices=[('c', 'Clubs'), ('d', 'Diamonds'), ('h', 'Hearts'), ('s', 'Spades')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet', models.DecimalField(decimal_places=2, max_digits=6)),
                ('seat_number', models.IntegerField(default=0)),
                ('picture', models.FileField(blank=True, upload_to='')),
                ('content_type', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player_game', to='chipcity.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_left', models.CharField(max_length=10)),
                ('card_right', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hand_game', to='chipcity.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='card_player', to='chipcity.player')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pot', models.IntegerField(default=0)),
                ('highest_bet', models.IntegerField(default=0)),
                ('current_player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='current_player', to='chipcity.player')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='round_game', to='chipcity.game')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('bet', 'Bet'), ('call', 'Call'), ('raise', 'Raise'), ('fold', 'Fold')], max_length=10)),
                ('bet_amount', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='action_player', to='chipcity.player')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='action_round', to='chipcity.round')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='flop1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flop1', to='chipcity.stuffcard'),
        ),
        migrations.AddField(
            model_name='game',
            name='flop2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flop2', to='chipcity.stuffcard'),
        ),
        migrations.AddField(
            model_name='game',
            name='flop3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flop3', to='chipcity.stuffcard'),
        ),
        migrations.AddField(
            model_name='game',
            name='river',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='river', to='chipcity.stuffcard'),
        ),
        migrations.AddField(
            model_name='game',
            name='turn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turn', to='chipcity.stuffcard'),
        ),
    ]
