# Generated by Django 5.0.1 on 2024-03-22 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('big_blind', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='big_blind', to=settings.AUTH_USER_MODEL)),
                ('small_blind', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='small_blind', to=settings.AUTH_USER_MODEL)),
                ('table_num', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='table_num', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money_in_hand', models.DecimalField(decimal_places=2, help_text='Money this user has in hand for this game', max_digits=10)),
                ('first_card', models.CharField(max_length=30)),
                ('second_card', models.CharField(max_length=30)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger', to='chipcity.game')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='participant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=200)),
                ('picture', models.FileField(blank=True, upload_to='')),
                ('content_type', models.CharField(blank=True, max_length=50)),
                ('wallet', models.DecimalField(decimal_places=2, max_digits=6)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
