# Generated by Django 3.2.24 on 2024-04-16 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chipcity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='picture',
        ),
        migrations.AlterField(
            model_name='player',
            name='chips',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='wallet',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
