# Generated by Django 3.2.24 on 2024-04-10 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chipcity', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Action',
        ),
    ]
