# Generated by Django 3.2.24 on 2024-04-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chipcity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='flop1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='flop2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='flop3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='river',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='turn',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='can_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='card_left',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='card_right',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='is_big_blind',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='is_small_blind',
            field=models.BooleanField(default=False),
        ),
    ]
