# Generated by Django 5.0.1 on 2024-03-28 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chipcity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='game',
            name='dealer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dealer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='num_of_players',
            field=models.IntegerField(default=2),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet', models.DecimalField(decimal_places=2, max_digits=6)),
                ('card_left', models.CharField(max_length=6)),
                ('card_right', models.CharField(max_length=6)),
                ('seat_number', models.IntegerField(default=0)),
                ('picture', models.FileField(blank=True, upload_to='')),
                ('content_type', models.CharField(blank=True, max_length=50)),
                ('pot', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player_game', to='chipcity.game')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='player', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flop_left', models.CharField(max_length=6)),
                ('flop_middle', models.CharField(max_length=6)),
                ('flop_right', models.CharField(max_length=6)),
                ('turn', models.CharField(max_length=6)),
                ('river', models.CharField(max_length=6)),
                ('current_player', models.IntegerField(default=0)),
                ('raise_amt', models.IntegerField(default=0)),
                ('current_bet', models.IntegerField(default=0)),
                ('player_pot', models.IntegerField(default=0)),
                ('pot', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='card_game', to='chipcity.game')),
                ('players', models.ManyToManyField(to='chipcity.player')),
                ('winner', models.ManyToManyField(related_name='winner', to='chipcity.player')),
            ],
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
