# Generated by Django 3.2.24 on 2024-04-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chipcity', '0002_auto_20240419_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='spectator',
        ),
        migrations.AddField(
            model_name='game',
            name='list_of_active_players',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
