# Generated by Django 5.0.1 on 2024-03-28 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chipcity', '0003_alter_game_big_blind_alter_game_pot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='pot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='table_num',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='table_num', to=settings.AUTH_USER_MODEL),
        ),
    ]
