# Generated by Django 3.2.24 on 2024-04-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chipcity', '0003_auto_20240419_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='spectator',
            field=models.BooleanField(default=False),
        ),
    ]
