# Generated by Django 5.0.1 on 2024-03-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chipcity', '0004_alter_game_pot_alter_game_table_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='pot',
            new_name='player_pot',
        ),
        migrations.RemoveField(
            model_name='card',
            name='current_bet',
        ),
        migrations.RemoveField(
            model_name='card',
            name='current_player',
        ),
        migrations.RemoveField(
            model_name='card',
            name='player_pot',
        ),
        migrations.RemoveField(
            model_name='card',
            name='players',
        ),
        migrations.RemoveField(
            model_name='card',
            name='pot',
        ),
        migrations.RemoveField(
            model_name='card',
            name='winner',
        ),
        migrations.AddField(
            model_name='game',
            name='current_bet',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='current_player',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='is_winner',
            field=models.ManyToManyField(related_name='winner', to='chipcity.game'),
        ),
    ]
