# Generated by Django 5.0.1 on 2024-03-30 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chipcity', '0005_rename_pot_player_player_pot_remove_card_current_bet_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='flop_left',
        ),
        migrations.RemoveField(
            model_name='card',
            name='flop_middle',
        ),
        migrations.RemoveField(
            model_name='card',
            name='flop_right',
        ),
        migrations.RemoveField(
            model_name='card',
            name='game',
        ),
        migrations.RemoveField(
            model_name='card',
            name='raise_amt',
        ),
        migrations.RemoveField(
            model_name='card',
            name='river',
        ),
        migrations.RemoveField(
            model_name='card',
            name='turn',
        ),
        migrations.RemoveField(
            model_name='game',
            name='big_blind',
        ),
        migrations.RemoveField(
            model_name='game',
            name='current_bet',
        ),
        migrations.RemoveField(
            model_name='game',
            name='current_player',
        ),
        migrations.RemoveField(
            model_name='game',
            name='dealer',
        ),
        migrations.RemoveField(
            model_name='game',
            name='num_of_players',
        ),
        migrations.RemoveField(
            model_name='game',
            name='pot',
        ),
        migrations.RemoveField(
            model_name='game',
            name='small_blind',
        ),
        migrations.RemoveField(
            model_name='game',
            name='table_num',
        ),
        migrations.RemoveField(
            model_name='player',
            name='card_left',
        ),
        migrations.RemoveField(
            model_name='player',
            name='card_right',
        ),
        migrations.RemoveField(
            model_name='player',
            name='is_winner',
        ),
        migrations.RemoveField(
            model_name='player',
            name='player_pot',
        ),
        migrations.AddField(
            model_name='card',
            name='rank',
            field=models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('T', 'Ten'), ('J', 'Jack'), ('Q', 'Queen'), ('K', 'King'), ('A', 'Ace')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='suit',
            field=models.CharField(choices=[('c', 'Clubs'), ('d', 'Diamonds'), ('h', 'Hearts'), ('s', 'Spades')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='game_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='players_connected',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='total_pot',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Hand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_left', models.CharField(max_length=10)),
                ('card_right', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hand_game', to='chipcity.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='card_player', to='chipcity.player')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pot', models.IntegerField(default=0)),
                ('highest_bet', models.IntegerField(default=0)),
                ('current_player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='current_player', to='chipcity.player')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='round_game', to='chipcity.game')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('bet', 'Bet'), ('call', 'Call'), ('raise', 'Raise'), ('fold', 'Fold')], max_length=10)),
                ('bet_amount', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='action_player', to='chipcity.player')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='action_round', to='chipcity.round')),
            ],
        ),
    ]
