# Generated by Django 5.0.1 on 2024-04-01 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chipcity', '0006_remove_card_flop_left_remove_card_flop_middle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='curr_round',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='flop1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flop1', to='chipcity.card'),
        ),
        migrations.AddField(
            model_name='game',
            name='flop2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flop2', to='chipcity.card'),
        ),
        migrations.AddField(
            model_name='game',
            name='flop3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flop3', to='chipcity.card'),
        ),
        migrations.AddField(
            model_name='game',
            name='river',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='river', to='chipcity.card'),
        ),
        migrations.AddField(
            model_name='game',
            name='turn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turn', to='chipcity.card'),
        ),
    ]
